# -*- coding: utf-8 -*-
"""DA_LotteWorld_강사작성답안_230627.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oC_eF705oqp1V9DUXRPGoyZuQUMJprTL
"""

import pandas as pd
from bs4 import BeautifulSoup
from urllib.request import urlopen
from selenium import webdriver
from datetime import datetime, timedelta
import time

#에러 나면 webdriver 호출하는 코드들을 아래 코드로 변경 및 라이브러리 추가
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service

driver=webdriver.Chrome(options=Options(), service=Service('C:/Users/thkim/Downloads/chromedriver_win32'))

pd.set_option('display.max_colwidth',None)
row = pd.Series(['날짜','운영시간','운휴 목록'])
df = pd.DataFrame(columns = row)
col = df.columns

#운휴목록
date = datetime.now()
url="https://adventure.lotteworld.com/kor/usage-guide/service/index.do?oprtDt="
for i in range(4):
    temp_date = (date+timedelta(days=i)).strftime("%Y%m%d")
    html = driver.get(url+temp_date)
    time.sleep(3)
    page = driver.page_source
    bs_obj = BeautifulSoup(page, "html.parser")

    closed_list = []
    for closed in bs_obj.find("ul", {"class":"holidayList"}).find_all("p", {"class":"txt"}):
        print(closed.text.splitlines())
        closed_list.append( ",".join(closed.text.splitlines()))

    row = pd.Series([datetime.strptime(temp_date, '%Y%m%d').strftime("%Y-%m-%d"),
        bs_obj.find("strong", {"class":"time time0"}).text + ":"
        +bs_obj.find("strong",{"class":"time time1"}).text+" ~ "
        +bs_obj.find("strong", {"class":"time time2"}).text + ":"
        +bs_obj.find("strong",{"class":"time time3"}).text,
        closed_list], index=col)
    df = df.append(row, ignore_index=True)
    #print(bs_obj.find("ul", {"class":"holidayList"}).text)

df

pd.set_option('display.max_colwidth',None)
row = pd.Series(['혜택 종류','기간','혜택', '혜택가'])
df2 = pd.DataFrame(columns = row)
col = df2.columns

url2 = "https://adventure.lotteworld.com/kor/price/benefit/information/list.do"
html = driver.get(url2)
page = driver.page_source
bs_obj = BeautifulSoup(page, "html.parser")

benefit = bs_obj.find("div", {"class":"benefitList"})
for event in benefit.find_all("a"):
    print(list(filter(None, event.text.splitlines())))
    temp = event.text.splitlines()
    del temp[0]
    del temp[1]
    row2 = pd.Series(temp, index=col)
    df2 = df2.append(row2, ignore_index=True)
    # print(list(filter(None, event.text.splitlines())))

df2

url2 = "https://adventure.lotteworld.com/kor/price/benefit/information/list.do"
html = driver.get(url2)
page = driver.page_source
bs_obj = BeautifulSoup(page, "html.parser")

benefit = bs_obj.find("div", {"class":"benefitList"})
for event in benefit.find_all("a"):
    print(event.text.splitlines())
    #print(list(filter(None, event.text.splitlines())))



