# -*- coding: utf-8 -*-
"""DA_네이버뉴스_강사작성답안_230612.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YmPEe6KPfn732X263J4pdPRNNXNI3bJL
"""

import pandas as pd
from bs4 import BeautifulSoup
from urllib.request import urlopen
from selenium import webdriver


#에러 나면 webdriver 호출하는 코드들을 아래 코드로 변경 및 라이브러리 추가
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service

driver=webdriver.Chrome(options=Options(), service=Service('C:/Users/thkim/Downloads/chromedriver_win32'))



#최신 버전에서 더 이상 지원하지 않는 호출 방식.
#driver = webdriver.Chrome('C:/Users/thkim/Downloads/chromedriver_win32')




url="https://news.naver.com/main/main.naver?mode=LSD&mid=shm&sid1=101"
html = driver.get(url)
page = driver.page_source
bs_obj = BeautifulSoup(page, "html.parser")


#열 헤더 리스트를 시리즈로 변환
header = ['제목','미리보기','링크']
row1 = pd.Series(header)

#빈 데이터 프레임에 열 헤더 설정
df = pd.DataFrame(columns=row1)

#시리즈에 열 헤더 붙일때 사용하기 위해서 열 헤더 따로 빼놓기
col = df.columns


arr = []
for article in bs_obj.find_all("div", {"class":"sh_text"}):
    row = pd.Series([article.select('a')[0].text,article.select_one("div.sh_text_lede").text,
                    article.select('a')[0].get('href')], index=col)
    df = df.append(row, ignore_index=True)



    #article.find("a",{"class":"sh_text_headline nclicks(cls_eco.clsart)"}).text)
    #article.select('a')[0].text   --select~~.text 되는 이유: [0] 하나만 가져왔기 때문이다.

    #굳이 비교를 하면
    #find_all <-> select
    #find <-> select_one


    #article.find("div",{"class":"sh_text_lede"}).text
    #article.select_one("div.sh_text_lede").text

df



